import {
    AccountCircle,
    AccountTree,
    Analytics,
    AutoAwesome,
    AutoFixHigh,
    Cable,
    ConfirmationNumber,
    CrisisAlert,
    Description,
    Devices,
    DynamicForm,
    FactCheck,
    Groups,
    Handshake,
    History,
    Home,
    Hub,
    Inbox,
    Info,
    ManageAccounts,
    MenuBook,
    Notifications,
    OutgoingMail,
    Password,
    Person,
    Policy,
    Quickreply,
    Send,
    Settings,
    SettingsApplications,
    SmartToy,
    SpaceDashboard,
    SupportAgent,
    Timer,
    Tune,
    ViewKanban,
    Webhook,
    Workspaces,
} from '@mui/icons-material'
import type { ElementType } from 'react'

import type { NavigationIcon } from './navigationRegistry'

export const navigationIconNames = {
    workspaceHub: 'Workspaces',
    operationsDashboard: 'Analytics',
    crossProjectBoard: 'ViewKanban',
    projectOperations: 'SupportAgent',
    projectOverview: 'Home',
    ticketManagement: 'ConfirmationNumber',
    knowledgeBase: 'MenuBook',
    projectNotifications: 'Notifications',
    intelligentOperations: 'AutoAwesome',
    humanAgentCollaboration: 'Handshake',
    automationRules: 'AutoFixHigh',
    agentManagement: 'SmartToy',
    integrationCenter: 'Cable',
    webhookSettings: 'Webhook',
    integrationRuntime: 'Hub',
    projectSettings: 'Tune',
    projectInformation: 'Info',
    projectMembers: 'Groups',
    ticketIntake: 'DynamicForm',
    slaPolicies: 'Timer',
    intakeQueues: 'Inbox',
    ticketTemplates: 'Description',
    quickReplies: 'Quickreply',
    notificationDelivery: 'Send',
    governanceCenter: 'Policy',
    platformDashboard: 'SpaceDashboard',
    projectGovernance: 'AccountTree',
    identityAccess: 'ManageAccounts',
    auditCenter: 'FactCheck',
    emergencyControls: 'CrisisAlert',
    systemSettings: 'SettingsApplications',
    publicConfiguration: 'Settings',
    emailDelivery: 'OutgoingMail',
    accountHub: 'AccountCircle',
    accountProfile: 'Person',
    accountSecurity: 'Password',
    trustedDevices: 'Devices',
    loginHistory: 'History',
} as const satisfies Record<NavigationIcon, string>

export const navigationIconComponents = {
    workspaceHub: Workspaces,
    operationsDashboard: Analytics,
    crossProjectBoard: ViewKanban,
    projectOperations: SupportAgent,
    projectOverview: Home,
    ticketManagement: ConfirmationNumber,
    knowledgeBase: MenuBook,
    projectNotifications: Notifications,
    intelligentOperations: AutoAwesome,
    humanAgentCollaboration: Handshake,
    automationRules: AutoFixHigh,
    agentManagement: SmartToy,
    integrationCenter: Cable,
    webhookSettings: Webhook,
    integrationRuntime: Hub,
    projectSettings: Tune,
    projectInformation: Info,
    projectMembers: Groups,
    ticketIntake: DynamicForm,
    slaPolicies: Timer,
    intakeQueues: Inbox,
    ticketTemplates: Description,
    quickReplies: Quickreply,
    notificationDelivery: Send,
    governanceCenter: Policy,
    platformDashboard: SpaceDashboard,
    projectGovernance: AccountTree,
    identityAccess: ManageAccounts,
    auditCenter: FactCheck,
    emergencyControls: CrisisAlert,
    systemSettings: SettingsApplications,
    publicConfiguration: Settings,
    emailDelivery: OutgoingMail,
    accountHub: AccountCircle,
    accountProfile: Person,
    accountSecurity: Password,
    trustedDevices: Devices,
    loginHistory: History,
} as const satisfies Record<NavigationIcon, ElementType>
