name: Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: pip install -r server/requirements-test.txt

      - name: Start services
        run: docker-compose up -d

      - name: Wait for API
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:8081/healthz >/dev/null; then
              echo "API is ready";
              exit 0;
            fi;
            echo "Waiting for API...";
            sleep 5;
          done;
          echo "API did not become ready in time";
          exit 1

      - name: Run smoke tests
        run: make smoke

      - name: Upload smoke reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-reports
          path: server/reports/*.html

      - name: Stop services
        if: always()
        run: docker-compose down
